export const types = {
  ACCOUNT_AJAX_BEGIN: 'ACCOUNT_AJAX_BEGIN',
  ACCOUNT_AJAX_END: 'ACCOUNT_AJAX_END',
  ACCOUNT_AJAX_ERROR: 'ACCOUNT_AJAX_ERROR',
  ACCOUNT_LOGIN: 'ACCOUNT_LOGIN',
  ACCOUNT_LOGOUT: 'ACCOUNT_LOGOUT'
}

export const actions = {
}
